### ISSUE TITLE
Netbox 2.10 compatibility?

### ISSUE THREAD

**Issue by jeremypng** [iDebugAll/nextbox-ui-plugin#37]
Looks like font-awesome needs to be migrated to material design icons and jquery needs to move from 3.4.1 to 3.5.1. The plugin won't load from the site page, but loads from the direct URL but is a little out of sorts because of the missing jquery I believe from looking at it this evening.

Want a PR or are you planning on updating it?

Thanks for the plugin!

**Comment by iDebugAll** [comment]
Hey @jeremypng, thank you for your feedback. The latest plugin version should actually be compatible with 2.10+ versions of NetBox. I have tested specifically with 2.10.1 (I use Docker community build for development).
jquery loading is a matter of improvement. Now the plugin tries to upload both 3.4.1 and 3.5.1 versions because of backward compatibility requirements:
```
        <script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
        <script src="{% static 'jquery/jquery-3.5.1.min.js' %}"></script>
```
Version selection based on NetBox version on server side during template rendering might be more pretty solution.

What is your NetBox and nextbox-ui-plugin versions? What error do you get on the Site page?

**Comment by jeremypng** [comment]
I have version 0.6.9 of the plugin and Netbox version 2.10.3. When I click the topology button on a site, the window pops up but says <hostname> refused to connect in the window. 

I have tried the plugin setting:
`"nextbox_ui_plugin": {
        "INITIAL_LAYOUT": "auto",
    }`

But that doesn't make a difference. It does load if I go straight to the plugin URL:
https://<hostname>/plugins/nextbox-ui/site_topology/143/

**Comment by iDebugAll** [comment]
@jeremypng, it seems to have something to do with the https enforcement on a latest NetBox release.
Could you open the NetBox itself via http and then try to reproduce the issue on the Site page?

>the window pops up but says refused to connect in the window

Are there any additional error messages in the web debugging console related to this (missing CSRF token or something)?

**Comment by jeremypng** [comment]
You are right. On that system the https is enforced by NGINX. It works fine on another install I have w/ NGINX with the same version of Netbox. I'll troubleshoot the broken one when I get the chance, but I don't think the problem is with the code at this time.

Thanks
